######################################################################
# Automatically generated by qmake (3.0) Fri Oct 6 20:07:32 2017
######################################################################

TEMPLATE = app
TARGET = applied_hw2_2
INCLUDEPATH += .
CONFIG += c++11

# Input
HEADERS += library.h \
    libraryui.h
SOURCES += library.cpp libraryClient-v2.cpp \
    libraryui.cpp
